### ISSUE TITLE
"To use the global `state`, or not to use, that is the question"

### ISSUE THREAD

**Issue by kasimte** [Junyoungpark/GTMARL-SC2EV#1]
From the Jupyter notebook in `examples`:

```
obs = env.get_obs() # give you a list that contains each agent's observaion
state = env.get_state() # The global state reserved for centralized exectuion
```

In the example, just random actions are chosen for each agent so neither is used. In the project, are agents allowed to use the global `state`? Or just their own partial observation?

Thanks!

**Comment by Junyoungpark** [comment]
Hi,

You can use either `state` (the global state) or `obs` for training your agent.

Here's some remark that you may want to know:
1. In general, using `state` implicitly assumes that your algorithm can only be executed in a centralized manner. 
2. On the other hand, the algorithms that use only `obs` (the partial observations of the agents) can be executed in a decentralized manner. 

So, in general, choosing which kind of information is determined by your application. When the case has some difficulty in gathering the state (basically a collection of all agents + alpha), the only choice is to use `obs` and introducing MARL techniques that you will cover in the class.

Thanks,
Jun

**Comment by Junyoungpark** [comment]
Do you mind if I rename the issue so that other classmates can recognize this issue easily?

**Comment by kasimte** [comment]
> Do you mind if I rename the issue so that other classmates can recognize this issue easily?

Not at all. Please do!

**Comment by Junyoungpark** [comment]
Thanks 👍
