### ISSUE TITLE
Should we be using pymarl to run experiments?

### ISSUE THREAD

**Issue by kasimte** [Junyoungpark/GTMARL-SC2EV#2]
I saw the oxwhirl folks published their framework, [pymarl](https://github.com/oxwhirl/pymarl), for running experiments in the SMAC environment. Is it recommended we use this as well?

**Comment by lesleychou** [comment]
Hi Junyoung, same question here! Pymarl seems opensource and runs well, but I'm confused if we could use it?

**Comment by Junyoungpark** [comment]
Hi @kasimte @lesleychou, yes you can use `pymarl` for your termproject.

**Comment by kasimte** [comment]
Thanks @Junyoungpark! Have you used pymarl before? Any tips for importing an agent model from the pymarl environment into the test code here would be greatly appreciated.

**Comment by Junyoungpark** [comment]
@kasimte, Unfortunately, I never used `pymarl` before :(

**Comment by kasimte** [comment]
@Junyoungpark No worries, thanks anyway!
