### ISSUE TITLE
Can I move "env.step(actions)" line in to my code block in test_model func?

### ISSUE THREAD

**Issue by yongjin-shin** [Junyoungpark/GTMARL-SC2EV#3]
Hi,

I guess 'num_runs' means number of episode to test.
My code block in test_model function is like this: 
(Apologize that I cannot find how to put indents here)

for i in range(num_runs):
     > env.reset()
     > while not terminated:
          >> state = get_state()
          >> actions = agent.get_action(state)
          >> reward, terminated, info = env.step(actions)

Since line 24 in your test code is out side of my while loop, I must step forward one more.
This causes info['battle_won'] to have false even if terminated is True from my while loop. 
Thus, can I just move/delete this line into my while loop?

Thanks,

**Comment by Junyoungpark** [comment]
Hi,

You can make an update as you mentioned to the code. please tell me whether you made the update on the code when you submit the final codes to me.

Thanks
