### ISSUE TITLE
Q. External Libraries

### ISSUE THREAD

**Issue by jason-huh** [Junyoungpark/GTMARL-SC2EV#6]
Can we use external libraries when importing a trained model?
If so, is it okay to specify them in `requirements.txt`. If not, how should we?

Thanks,

**Comment by Junyoungpark** [comment]
@iriszero, can you tell me which kind of the external libraries will be used??
Unless the libraries are not difficult to be installed on our lab servers (basically, windows and Linux machines), it will be okay.

**Comment by jason-huh** [comment]
Thank you!
As of now, we're going to use only [Sacred](https://github.com/IDSIA/sacred). We will add `requirements.txt` file with the exact version of the libraries we use.
